function requirecolarray(var,collength)

    if size(var,2) ~= 1        
        ME = MException('FvmLab:TypeChecker:NoColumnArray',...
           ['\nFVMLab:TypeChecker:NoColumnArray',...
            '\nThe supplied data is not ordered in a column'...
            '\n']);
        throwAsCaller(ME);
    end
    if nargin == 2 && size(var,1) ~= collength
        ME = MException('FVMLab:TypeChecker:UnexpectedColLength',...
           ['\nFVMLab:TypeChecker:UnexpectedColLength',...
            '\nThe supplied data does not have the required column length of %g'...
            '\n'],collength);
        throwAsCaller(ME);
    end
        
end